### ISSUE TITLE
Installation failed for Magento 2.1.2

### ISSUE THREAD

**Issue by steven-fernandez** [DavidBelicza/magento2-server-configuration#2]
I tried it on a fresh installation of ubuntu 16.04 and changed the version to Magento 2.1.2 but installation fails.

**Comment by DoveID** [comment]
Can you give more details about the problem? Did you get any error message?

**Comment by steven-fernandez** [comment]
Hi David,

A lot of things didn't install via composer.

Might be a version issue

**Comment by MrDaar** [comment]
This ticket is pretty old, and looks like it's no longer relevant. Shall we close it?

**Comment by DavidBelicza** [comment]
I think it is fixed in #22
