### ISSUE TITLE
css & javascript not load on magento 2.1.7 & 2.1.5

### ISSUE THREAD

**Issue by blackbone23** [DavidBelicza/magento2-server-configuration#20]
I just change release version to both 2.1.7 and 2.1.5 but css and javascript not load on my vps..

**Comment by blackbone23** [comment]
If there is a same way to configure magento2 version 2.1.1, 2.1.5 and 2.1.7 so i made my mistake for not set the cron job before access the frontend

**Comment by DavidBelicza** [comment]
Fixed: #22
