### ISSUE TITLE
[ErrorException]zlib_decode(): data error

### ISSUE THREAD

**Issue by raysham** [DavidBelicza/magento2-server-configuration#3]
Composer issue as below:

 [ErrorException]           
  zlib_decode(): data error  
                             

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [packages1] ... [packagesN]

There is an error during sample data deployment.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)

                                            
  [Composer\Downloader\TransportException]  
  Content-Length mismatch                   
                                            

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

could anyone help on the case?
i am a beginer in linux and magento. Just hope to get magento installed.

Thanks so much.

**Comment by DavidBelicza** [comment]
Hello,

Did you modify the configuration or the installation files?

**Comment by DavidBelicza** [comment]
Closed because of inactivity.
