### ISSUE TITLE
install.sh parsing issue

### ISSUE THREAD

**Issue by hakabe** [DavidBelicza/magento2-server-configuration#4]
I edited the values with standard letters and numbers - yet I was able to produce following scenario after running install.sh

Packages installed fine.

CONFIGURATION: NGINX FOR MAGENTO 2

Missing parameters.
1st parameter is magento release
2nd parameter is magento folder name what is same as the domain address
3rd parameter is magento linux user (it will create it)
4th parameter is magento linux password (it will create it)
Try this: magento-prepare.sh 2.0.7 mywebshop.com magento magento

CONFIGURATION: MAGENTO CONNECT KEYS

1st parameter is magento domain
2nd parameter is magento connect public key
3rd parameter is magento connect private key
Try this: auth-json.sh magento.com 123456789 123456789

INSTALLATION: MAGENTO 2 COMPOSER PROJECT

1st parameter is magento domain
Try this: magento-injection.sh mywebshop.com

INSTALLATION: THE MAGENTO 2

1st parameter is magento domain
2nd parameter is magento domain with http or https
3rd parameter is database host
4th parameter is database name
5th parameter is database user
6th parameter is database password
7th parameter is admin email
8th parameter is admin login name
9th parameter is admin login password
10th parameter is language code
11th parameter is currency code
Try this: magento-install.sh mywebshop.com http://mywebshop.com/ localhost magen           to root secret123 admin@mywebshop.com admin admin123 en_US USD

INSTALLATION: MAGENTO 2 SAMPLE DATA DEMO STORE

1st parameter is magento domain
2nd parameter is language code
Try this: magento-sample.sh mywebshop.com

**Comment by DavidBelicza** [comment]
Hello,

What was the modified content?

**Comment by DavidBelicza** [comment]
Closed because of long inactivity.
