### ISSUE TITLE
INSTALLATION: MAGENTO 2 COMPOSER PROJECT

### ISSUE THREAD

**Issue by techmela** [DavidBelicza/magento2-server-configuration#5]
I received the following errors when trying to install the Magento 2 Compose Project

CONFIGURATION: MAGENTO CONNECT KEYS
rm: cannot remove '/var/www/html/mymelaglobal.com/webroot/auth.json': No such file or directory

INSTALLATION: MAGENTO 2 COMPOSER PROJECT
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 73 installs, 0 updates, 0 removals
  - Installing magento/magento-composer-installer (0.1.8) Downloading: 100%         
  - Installing braintree/braintree_php (2.39.0) Downloading: 100%         
  - Installing magento/zendframework1 (1.12.16) Downloading: 100%         
  - Installing colinmollenhour/credis (1.6) Downloading: 100%         
  - Installing colinmollenhour/php-redis-session-abstract (v1.1) Downloading: 100%         
  - Installing justinrainbow/json-schema (1.6.1) Downloading: 100%         
  - Installing symfony/console (v2.6.13) Downloading: 100%         
  - Installing symfony/process (v2.8.6) Downloading: 100%         
  - Installing symfony/finder (v2.8.6) Downloading: 100%         
  - Installing seld/jsonlint (1.4.0) Downloading: 100%         
  - Installing composer/composer (1.0.0-alpha10) Downloading: 100%         
  - Installing magento/composer (1.0.2) Downloading: Connecting...
                                                                                                  
  [Composer\Downloader\TransportException]                                                        
  Invalid credentials for 'https://repo.magento.com/archives/magento/composer/magento-composer-1  
  .0.2.0.zip', aborting.                                                                          
                                                                                                  

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

INSTALLATION: THE MAGENTO 2
Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.
INSTALLATION: MAGENTO 2 SAMPLE DATA DEMO STORE
Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information

                                                                               
  [Composer\Downloader\TransportException]                                     
  Invalid credentials for 'https://repo.magento.com/packages.json', aborting.  
                                                                               

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.root@ubuntu16:/magento2-server-configuration#

**Comment by DavidBelicza** [comment]
There is a newer installer, it does not download the developer release but creates and installs the composer project #22
