### ISSUE TITLE
Can't upgrade Magento from admin... How can I fix that?

### ISSUE THREAD

**Issue by katiakweb** [DavidBelicza/magento2-server-configuration#6]

**Comment by DavidBelicza** [comment]
Hello,

How do you mean you can not? Is there an error message?

**Comment by katiakweb** [comment]
Check the images in attachment.
I can see my keys in backend, but if I try upgrade in the backend or by SSH I get this errors.
![problem-upgrade](https://user-images.githubusercontent.com/13817990/28759206-af88a4b8-7570-11e7-8121-b22116c90bcb.jpg)
![problem-upgrade1](https://user-images.githubusercontent.com/13817990/28759220-e1785e46-7570-11e7-9939-d22a29bd2b2b.jpg)

**Comment by DavidBelicza** [comment]
It is not related to this server installer.
